### ISSUE TITLE
Table width too small, requires horizontal scrolling

### ISSUE THREAD

**Issue by eppeters** [iann0036/permissions.cloud#1]
Hello, Ian,

Thanks so much for putting this project together. I think this and your other IAM data projects are fantastic.

For a while, though, I thought permissions.cloud was just a list of the permissions/actions we know about and that it didn't display the mappings between permissions/actions. But turns out that's just because of some kind of display bug I'm experiencing.

![image](https://user-images.githubusercontent.com/5383250/133786584-6c44f4ff-9f4f-4143-bfae-f65b25ac6755.png)

The tables' display area is so small that I can't see any of the useful columns unless I go all the way to the bottom and scroll right with a tiny horizontal scroll bar.

My resolution is 2560x1440.

I'll help out with this if you don't get to it first. Thanks.

**Comment by iann0036** [comment]
Thanks for reaching out @eppeters!

Feel free to give it a go. It'll likely just be CSS grid changes to be made (and I'm no good with those!).
