### ISSUE TITLE
Consider text compression in CloudFront 

### ISSUE THREAD

**Issue by exoego** [iann0036/permissions.cloud#19]
It appears that Amazon CloudFront is used to serve https://aws.permissions.cloud/

I've noticed that your text files (JSON/JS/CSS) are returned in a plain format, instead of one in a compressed format (GZIP or Brotli).
Enabling compression will speed up network download and save your bandwidth == AWS payment 💵

**Comment by iann0036** [comment]
Applied as indicated. Thanks for the recommendation!
