### ISSUE TITLE
Allow searching for managed policies containing a permission

### ISSUE THREAD

**Issue by tomelliff** [iann0036/permissions.cloud#6]
This is a super useful tool and I've started linking colleagues to this rather than AWS' own IAM docs as it looks much clearer plus has the benefit of listing managed IAM policies without them needing to log into the AWS console to view.

One thing that would be useful for me would be to be able to search all managed policies for a specific permission. Right now I go to the source repo and search via GitHub (eg like [this](https://github.com/iann0036/iam-dataset/search?q=ImportExternalIdPCertificate)) but it would be a nicer user experience if you could go from eg [this link](https://aws.permissions.cloud/iam/sso-directory#sso-directory-ImportExternalIdPCertificate) and then click into a permission to see managed policies containing the effective action.

**Comment by avoidik** [comment]
that's amazing that we have such a fantastic feature request already, another use-case is when AWS is deprecating one big managed policy in favor of multiple fine-grained policies, and it is not always clear where to find particular action now
